### ISSUE TITLE
fix button position bug on location study table tab

### ISSUE THREAD

**Issue by tyarkoni** [neurosynth/neurosynth-web#80]
The "select all" and "deselect all" buttons show up fine on most pages, but on the location tab, they're not aligned properly--presumably because they're floating and interfere with the radius adjustment bar just above. I'm not assigning this to a milestone because it's purely cosmetic and I'm planning to release the custom analysis functionality tomorrow or Thursday whether or not it's fixed. But take a look when you have a chance.

**Comment by skept** [comment]
Done.

**Comment by tyarkoni** [comment]
Reopening because the change fixed the buttons but seemed to have made it so the rows in the table are no longer highlighted properly (they still get highlighted when you click on a row manually).

**Comment by tyarkoni** [comment]
Had a chance to look at this? Still seems to be a problem. Only happens on the Locations page.
